### ISSUE TITLE
Migrate to fuse3 ?

### ISSUE THREAD

**Issue by twolife** [OpenMandrivaSoftware/ossp#13]
osspd currently depends on libfuse2, more specifically it target a very old API : `#define FUSE_USE_VERSION 28`
That's perfectly fine, as long as linux distributions still ships libfuse2 in addition to the more recent libfuse3 (first released in 2016)

I recently see a call to remove fuse2 from Debian https://lists.debian.org/debian-devel/2024/08/msg00177.html
The consensus of this email thread is that for the near future, libfuse2 is here to stay. But the next time the topic will be raised, I fear another outcome. And I would be very sad if osspd would be removed from Debian because of that.

So, maybe it is possible to act now and avoid being sad later ^^
Has somebody already looked to port osspd to libfuse3 ?
Is anybody but me interested in such a thing ?

**Comment by davidebeatrici** [comment]
I'm definitely interested and I'll take a look.

And thank you for bringing the issue to our attention, of course.
